### ISSUE TITLE
v0.4.0 features - HSCS support

### ISSUE THREAD

**Issue by kpachhai** [hashgraph/hedera-metamask-snaps#395]
### Problem

Get all the Hedera Token Service features on the snap as part of v0.3.0

### Solution

HSCS features:
- [x] [Create a smart contract](https://github.com/hashgraph/hedera-metamask-snaps/issues/389)
- [x] [Update a smart contract](https://github.com/hashgraph/hedera-metamask-snaps/issues/390)
- [x] [Delete a smart contract](https://github.com/hashgraph/hedera-metamask-snaps/issues/391)
- [x] [Call a smart contract function](https://github.com/hashgraph/hedera-metamask-snaps/issues/392)
- [x] [Execute ethereum transaction](https://github.com/hashgraph/hedera-metamask-snaps/issues/393)
- [x] [Get smart contract details](https://github.com/hashgraph/hedera-metamask-snaps/issues/394)
