### ISSUE TITLE
v0.5.0 features - HCS support 

### ISSUE THREAD

**Issue by kpachhai** [hashgraph/hedera-metamask-snaps#491]
### Problem

Get all the Hedera Consensus Service features on the snap as part of v0.5.0

### Solution

HCS features:
- [x] [Create a new topic](https://github.com/hashgraph/hedera-metamask-snaps/issues/486)
- [x] [Update a topic](https://github.com/hashgraph/hedera-metamask-snaps/issues/487)
- [x] [Submit a message](https://github.com/hashgraph/hedera-metamask-snaps/issues/488)
- [x] [Delete a topic](https://github.com/hashgraph/hedera-metamask-snaps/issues/489)
- [x] [Get topic info](https://github.com/hashgraph/hedera-metamask-snaps/issues/490)
