### ISSUE TITLE
v0.2.0 features

### ISSUE THREAD

**Issue by kpachhai** [hashgraph/hedera-metamask-snaps#50]
### Problem

Get all the features implemented on the snap as part of v0.2.0

### Solution

Basic features:
- [x] Send HBAR to AccountID
- [x] Send HBAR to an AccountID with Memo
- [x] Create a new non-custodial Hedera Network account
- [x] View HBAR balance
- [x] Get Hedera Network Account Info
- [x] Use a Metamask account for transactions on the Hedera mainnet Network
- [x] Connect to a Hardware wallet for Digital Asset
- [x] Import a Hedera Network Account using a private key

Advanced Features
- [x] Send HBAR to an EVM address
- [x] Auto-create a Hedera Network Account for a public key
- [x] Auto-create an account for an EVM address
- [x] [View Transactions history](https://github.com/hashgraph/hedera-metamask-snaps/issues/51)
- [x] [Approve and delete an allowance](https://github.com/hashgraph/hedera-metamask-snaps/issues/52)
- [x] Transfer Digital Assets(both fungible and non-fungible tokens) between Hedera network accounts
- [x] [Delete an account](https://github.com/hashgraph/hedera-metamask-snaps/issues/53)
- [x] [Stake and Unstake HBAR to and from Hedera Network nodes](https://github.com/hashgraph/hedera-metamask-snaps/issues/54)

Miscellaneous features
- [x] [Sign any message using user's snap account](https://github.com/hashgraph/hedera-metamask-snaps/issues/31)

Hedera Token Service Features
- [x] Associate fungible and non-fungible tokens to an account
