### ISSUE TITLE
v0.3.0 features - HTS support

### ISSUE THREAD

**Issue by kpachhai** [hashgraph/hedera-metamask-snaps#90]
### Problem

Get all the Hedera Token Service features on the snap as part of v0.3.0

### Solution

HTS features:
- [x] [Create a token(both fungible and non-fungible tokens)](https://github.com/hashgraph/hedera-metamask-snaps/issues/94)
- [x] [Update a token and its properties](https://github.com/hashgraph/hedera-metamask-snaps/issues/91)
- [x] Transfer tokens
- [x] [Delete a token](https://github.com/hashgraph/hedera-metamask-snaps/issues/92)
- [x] [Mint a token](https://github.com/hashgraph/hedera-metamask-snaps/issues/93)
- [x] [Burn a token](https://github.com/hashgraph/hedera-metamask-snaps/issues/95)
- [x] [Freeze an account](https://github.com/hashgraph/hedera-metamask-snaps/issues/96)
- [x] [Unfreeze an account](https://github.com/hashgraph/hedera-metamask-snaps/issues/97)
- [x] [Enable/Disable KYC account flag](https://github.com/hashgraph/hedera-metamask-snaps/issues/98)
- [x] Associate tokens to an account
- [x] [Disassociate tokens from an account](https://github.com/hashgraph/hedera-metamask-snaps/issues/99)
- [x] [Pause/unpause a token](https://github.com/hashgraph/hedera-metamask-snaps/issues/100)
- [x] [Wipe a token](https://github.com/hashgraph/hedera-metamask-snaps/issues/101)
- [x] [Atomic Swaps between different tokens](https://github.com/hashgraph/hedera-metamask-snaps/issues/102)
